### ISSUE TITLE
Can you look at this?

### ISSUE THREAD

**Issue by aasutossh** [sam-moshenko/drf_depth_problem#1]
I am using nested serializers as well as depth option.
https://github.com/beda-software/drf-writable-nested/issues/119

**Comment by aasutossh** [comment]
Check out #2 I modified this project to show my issue.

**Comment by sam-moshenko** [comment]
Sorry man, I am out of context right now. Haven't touched django in quite some time. I want to return to one project on django at some point though. Thank you for your contribution anyways, it may become handy later.👍

**Comment by aasutossh** [comment]
I thought you might have some idea about it. It's causing me trouble. No worries. Be safe.
